spring.application.name=Ulkona

spring.datasource.url=jdbc:postgresql://localhost:5432/ulkona
spring.datasource.username=ulkona
spring.datasource.password=ulkona

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info