### Application status
GET http://localhost:8080/api

### Health
GET http://localhost:8080/actuator/health

### Create a product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "sku": "ULK-BAG-001",
  "name": "Hiking Backpack 45L",
  "brand": "Ayacucho",
  "category": "BACKPACK",
  "price": 129.99
}

### Find all products
GET http://localhost:8080/api/products